
spring.datasource.url=jdbc:postgresql://<IP-адрес>:<порт>/<имя_бд>
spring.datasource.username=<username>
spring.datasource.password=<password>
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true